### ISSUE TITLE
Error building as part of other project

### ISSUE THREAD

**Issue by laanwj** [apoelstra/rust-secp256k1#7] opened 2015-11-05 08:05 UTC
I'm trying to cargo build `rust-bitcoin` on a fresh ubuntu 15.10 VM with `cargo-nightly` and `rust-nightly` from [hansjorg](https://launchpad.net/~hansjorg/+archive/ubuntu/rust) installed, but get the following:
```
   Compiling secp256k1 v0.4.1
   Compiling serde_json v0.6.0
Build failed, waiting for other jobs to finish...
failed to run custom build command for `secp256k1 v0.4.1`
Process didn't exit successfully: `/home/ubuntu/projects/rust-bitcoin/target/debug/build/secp256k1-fa47f47f366c8111/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-unknown-linux-gnu")
debug=true opt-level=0
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/src" "-g" "-DUSE_NUM_NONE=1" "-DUSE_FIELD_INV_BUILTIN=1" "-DUSE_SCALAR_INV_BUILTIN=1" "-DUSE_FIELD_10X26=1" "-DUSE_SCALAR_8X32=1" "-DUSE_ENDOMORPHISM=1" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_RECOVERY=1" "-o" "/home/ubuntu/projects/rust-bitcoin/target/debug/build/secp256k1-fa47f47f366c8111/out/depend/secp256k1/src/laxder_shim.o" "-c" "depend/secp256k1/src/laxder_shim.c"
ExitStatus(Code(1))


command did not execute successfully, got: exit code: 1



--- stderr
In file included from depend/secp256k1/src/laxder_shim.c:15:0:
depend/secp256k1/contrib/lax_der_parsing.h:48:23: fatal error: secp256k1.h: No such file or directory
compilation terminated.
thread '<main>' panicked at 'explicit panic', /home/ubuntu/.cargo/registry/src/github.com-0a35038f75765ae4/gcc-0.3.19/src/lib.rs:771

```
I can build rust-secp256k1 fine separately, so it looks like a path issue

**Comment by apoelstra** [comment] 2015-11-05 12:50
I can repro on my documentation server (which is currently broken by it) but not on my local system (which is using rust-secp as a dependency for several projects). Not sure yet what the difference is.

**Comment by apoelstra** [comment] 2015-11-08 20:24
I can reproduce now -- uninstalling libsecp from /usr/local did it. Sorry for the delay. I'll get this fixed now.

**Comment by apoelstra** [comment] 2015-11-08 21:15
Fixed. I had updated build.rs for a missing include directory but not published to cargo; my local project that depended on rust-secp continued to work because I had the needed files in /usr/local, hence my not noticing. Sorry about that.

**Closed by apoelstra** 2015-11-08 21:15 UTC
